### ISSUE TITLE
Not enough space in the temporary send buffer.

### ISSUE THREAD

**Issue by radius314** [frgtn/rpcapd-linux#3]
I'm getting this error periodically and then I have to restart in order to have the capture work properly.  Any assistance would be greatly appreciated.

**Comment by frgtn** [comment]
The error originates from libpcap `sock_bufferize` function.
Can you provide more details? Things to include: full command with args you're using to launch rpcapd, full output of the program and what packets are you trying to capture. Also linux distro and kernel version would be good.

**Comment by guyharris** [comment]
Try using the standard libpcap client and server code in [its GitHub repository](https://github.com/the-tcpdump-group/libpcap); file any issues found with that code in its Issues section.
